import type { Base } from './type'

export const modalText: Base = {
  familyname_kanji: '姓(漢字)',
  firstname_kanji: '名(漢字)',
  familyname_hurigana_hira: '姓(ふりがな)',
  firstname_hurigana_hira: '名（ひりがな）',
  familyname_hurigana_kata: '姓(フリガナ)',
  firstname_hurigana_kata: '名（フリガナ）',
  familyname_hurigana_roman: '姓(ローマ字)',
  firstname_hurigana_roman: '名（ローマ字）',
  dateofbirth_year: '生年月日(年) 例)2000',
  dateofbirth_month: '生年月日(月) 例)07',
  dateofbirth_day: '生年月日(日) 例)07',
  zip_code1: '郵便番号前3桁（自宅）●●●-◯◯◯◯',
  zip_code2: '郵便番号後4桁（自宅）◯◯◯-●●●●',
  prefecture: '都道府県（自宅）',
  municipalities: '市区町村（自宅）',
  town_name: '町名（自宅）',
  block_number_kanji: '番地（自宅、漢字)',
  block_number_kata: '番地（自宅、カタカナ)',
  building_name: 'ビル・マンション名（自宅）',
  email: 'メールアドレス',
  tel1: '電話番号1 ●●●-◯◯◯◯-◯◯◯◯',
  tel2: '電話番号2 ◯◯◯-●●●●-◯◯◯◯',
  tel3: '電話番号3 ◯◯◯-◯◯◯◯-●●●●',
  tel_landline1: '自宅電話番号1 ●●●-◯◯◯◯-◯◯◯◯',
  tel_landline2: '自宅電話番号2 ◯◯◯-●●●●-◯◯◯◯',
  tel_landline3: '自宅電話番号3 ◯◯◯-◯◯◯◯-●●●●',
  school_name: '学校名',
  school_zip_code1: '郵便番号前3桁（学校）●●●-◯◯◯◯',
  school_zip_code2: '郵便番号後4桁（学校）◯◯◯-●●●●',
  school_prefecture: '都道府県（学校）',
  school_municipalities: '市区町村（学校）',
  school_town_name: '町名（学校）',
  school_block_number: '番地（学校）',
  school_building_name: 'ビル・マンション名（学校）',
  school_tel1: '電話番号1（学校） ●●●-◯◯◯◯-◯◯◯◯',
  school_tel2: '電話番号2（学校） ◯◯◯-●●●●-◯◯◯◯',
  school_tel3: '電話番号3（学校） ◯◯◯-◯◯◯◯-●●●●',
}
